# Aljabar Matriks

1. Berikan penjelasan tentang apa itu matriks
2. Operasi matriks penjumlahan,pengurangan, perkalian dan transpose
3. Buat Program untuk mengalikan A dan B
4. Cara mengalikan Matriks

Saya disuruh membuat contoh Matriks A,B dan D dengan baris 3 kolom 3 dan matrik C dengan baris 2 kolom 3
 Matriks A =mxn
 Matriks B =nxk

In [ ]:
import numpy as np
A = np.array([[3,2,4],[1,3,2],[2,3,5]])
print(A)
print()
B = np.array([[1,1,2],[1,4,2],[1,1,3]])
print(B)
print()
C = np.array ([[2,3],[1,3],[2,4]])
print(C)
print()
D = np.array([[1,1,4],[1,3,2],[2,1,2]])
print(D)

[[3 2 4]
 [1 3 2]
 [2 3 5]]

[[1 1 2]
 [1 4 2]
 [1 1 3]]

[[2 3]
 [1 3]
 [2 4]]

[[1 1 4]
 [1 3 2]
 [2 1 2]]


## NO 1

1. Matriks adalah Susunan Bilangan yang ditulis dalam baris dan kolom yang dibatasi oleh tanda kurung. didalam matriks itu ada elemen yaitu kolom dan baris. kolom itu susunan angka atau bilangan yang tegak dalam matriks sedangkan baris itu susunan angka atau bilangan yang mendatar dalam matriks. ada juga yang namanya ordo,Ordo matriks merupakan banyaknya baris dan kolom yang terdapat pada suatu matriks. misal dalam suatu matriks kolom 3 dan baris 2, ordo nya itu 2x3

## No 2

2. A. Operasi Penjumlahan matriks merupakan operasi penjumlahan dalam matriks yang menjumlahkan komponen-komponen yang sama tempatnya. untuk menjumlahkan syaratnya ordo dari masing-masing matriks harus sama

In [ ]:
# contoh: (A+B)
A = np.array([[3,2,4],[1,3,2],[2,3,5]])
B = np.array([[1,1,2],[1,4,2],[1,1,3]])
print(A)
print()
print(B)

[[3 2 4]
 [1 3 2]
 [2 3 5]]

[[1 1 2]
 [1 4 2]
 [1 1 3]]


In [ ]:
E = np.array([[3+1,2+1,4+2],[1+1,3+4,2+2],[2+1,3+1,5+3]])
print(E)

[[4 3 6]
 [2 7 4]
 [3 4 8]]


B. Operasi Pengurangan matriks merupakan operasi pengurangan dalam matriks yang mengurangkan komponen-komponen yang sama tempatnya. sama seperti operasi penjumlahan matriks syarat nya ordonya harus sama sehingga bisa dioperasikan

In [ ]:
# contoh: (B-D)
B = np.array([[1,1,2],[1,4,2],[1,1,3]])
print(B)
print()
D = np.array([[1,1,4],[1,3,2],[2,1,2]])
print(D)

In [ ]:
F =np.array([[1-1,1-1,2-4],[1-1,4-3,2-2],[1-2,1-1,3-2]])
print(F)

C. Operasi Perkalian matriks adalah operasi mengalikan  matriks mengalikan setiap elemen baris pada matriks pertama dengan elemen kolom pada matriks kedua. syarat mengalikan matriks itu kolom dari matriks pertama harus sama dengan baris dari matriks kedua misal matriks A ordo nya 2x3 dan matriks B ordo 3x3

In [ ]:
# contoh: (AXD)
A = np.array([[3,2,4],[1,3,2],[2,3,5]])
print(A)
print()
D = np.array([[1,1,4],[1,3,2],[2,1,2]])
print(D)

[[3 2 4]
 [1 3 2]
 [2 3 5]]

[[1 1 4]
 [1 3 2]
 [2 1 2]]


In [ ]:
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

# Perkalian matriks secara manual
for i in range(len(A)):  # Loop baris matriks A
    for j in range(len(D[0])):  # Loop kolom matriks B
        for k in range(len(D)):  # Loop kolom matriks A/baris matriks B
            result[i][j] += A[i][k] * D[k][j]

# Menampilkan hasil
print("Hasil perkalian matriks A dan D:")
for row in result:
    print(row)

Hasil perkalian matriks A dan D:
[13, 13, 24]
[8, 12, 14]
[15, 16, 24]


D. Operasi transpose matriks merupakan matriks baru yang diperoleh dengan cara menukar elemen-elemen baris menjadi elemen kolom atau sebaliknya.

In [ ]:
# contoh: (AT)
A = np.array([[3,2,4],[1,3,2],[2,3,5]])
print(A)

In [ ]:
# A.trans =
N= np.array([[3,1,2],[2,3,3],[4,2,5]])
print(N)

## NO 3

3. Mengalikan matriks A dengan matriks B

In [ ]:
A = np.array([[3,2,4],[1,3,2],[2,3,5]])
print(A)
print()
B = np.array([[1,1,2],[1,4,2],[1,1,3]])
print(B)

In [ ]:
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

# Perkalian matriks secara manual
for i in range(len(A)):  # Loop baris matriks A
    for j in range(len(B[0])):  # Loop kolom matriks B
        for k in range(len(B)):  # Loop kolom matriks A/baris matriks B
            result[i][j] += A[i][k] * B[k][j]

# Menampilkan hasil
print("Hasil perkalian matriks A dan B:")
for row in result:
    print(row)

## NO 4

4. Untuk mengalikan matriks ada syaratnya.Syarat perkalian matriks itu Baris = kolom artinya barisnya harus sama dengan kolom dan cara nya itu baris dikali kolom