# Determinan Matriks


- Sifat-sifat Determinan
- Mancari fungsi dipython menghitung determinan identitas
- matriks Identitas 2x2 dan 3x3 dan cari determinannya
- Menghitung determinan matriks dan invers matriks
  menghitung invers matriks 5x5
  

2.merubah baris merubah tanda determinan

In [ ]:
import numpy as np
A= np.array([[2,3],[4,3]])
print(A)
A=np.linalg.det(A)
print(f'Determinannya:',{A})


[[2 3]
 [4 3]]
Determinannya: {-6.0}


In [ ]:
import numpy as np
c= np.array([[1,2,1],[3,1,2],[2,1,2]])
print(c)
c=np.linalg.det(c)
print(f'Determinannya:',{c})
c= round(c)
print(c)

[[1 2 1]
 [3 1 2]
 [2 1 2]]
Determinannya: {-3.000000000000001}
-3


In [ ]:
import numpy as np
e= np.array([[1,2,1],[2,4,2],[2,1,2]])
print(e)
#Determinan
e=np.linalg.det(e)
print(f'Determinannya:',{e})

[[1 2 1]
 [2 4 2]
 [2 1 2]]
Determinannya: {0.0}


In [ ]:
import numpy as np
g= np.array([[6,2,4],[2,4,2],[4,2,4]])
print(g)
g=np.linalg.det(g)
print(f'Determinannya:',{g})

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinannya: {24.000000000000014}


In [ ]:
import numpy as np
h= np.array([[6,8],[4,2]])
print(h)
h=np.linalg.det(h)
print(f'Determinannya:',{h})


[[6 8]
 [4 2]]
Determinannya: {-19.999999999999996}


- ketika ada Matriks A dan B dengan ordo yang sama, matriks B Merupakan kelipatan dari matriks A dan determinan dari matriks A sudah diketahui maka determinan B = Kelipatan dari elemen matriks dikali hasil determinan matriks A.
contoh: $2^{3}$.3

In [ ]:
import numpy as np
D= np.array([[3,1,2],[1,2,1],[2,1,2]])
g= np.array([[6,2,4],[2,4,2],[4,2,4]])
print(D)
D=np.linalg.det(D)
print(f'Determinannya:',{D})
print()
print(g)
g=np.linalg.det(g)
print(f'Determinannya:',{g})

[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinannya: {3.000000000000001}

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinannya: {24.000000000000014}


A=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   3 &4\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

A2=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   7 &5\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

A3=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   4 &1\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

In [ ]:
import numpy as np
a= np.array([[4,1],[2,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})

[[4 1]
 [2 1]]
Determinannya: {2.0}


In [ ]:
#Mtriks Segitiga atas
import numpy as np
k= np.array([[4,1,3],[0,2,1],[0,0,1]])
print(k)
k=np.linalg.det(k)
print(f'Determinannya:',{k})

[[4 1 3]
 [0 2 1]
 [0 0 1]]
Determinannya: {7.999999999999998}


In [ ]:
l= np.array([[1,0,0],[2,1,0],[4,1,3]])
print(l)
l=np.linalg.det(l)
print(f'Determinannya:',{l})

[[1 0 0]
 [2 1 0]
 [4 1 3]]
Determinannya: {2.9999999999999996}


Determinan matriks C= det(AB)

In [ ]:
import numpy as np
a= np.array([[2,1],[1,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})
print()
b= np.array([[1,1],[1,1]])
print(b)
b=np.linalg.det(b)
print(f'Determinannya:',{b})

[[2 1]
 [1 1]]
Determinannya: {1.0}

[[1 1]
 [1 1]]
Determinannya: {0.0}


In [ ]:
C=np.array([[3,3],[2,2]])
print(C)
C=np.linalg.det(C)
print(f'Determinannya:',{C})


[[3 3]
 [2 2]]
Determinannya: {0.0}


# Menghitung determinan matriks dan invers matriks menghitung invers matriks 5x5

Menghitung determinan matriks dan invers matriks menghitung invers matriks 5x5

pick row z= zij*cij+zij*cij...zin*cin

rumus  $z^{-1}$ = 1/det matriks.$z^{T}$

z= $\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   4&2&1&1&3\\
    3& 2& 1&2&2\\
    4& 1 & 1&1&1\\
    1&3&4&1&2\\
    2&2&1&1&3 \end{array}\right]
\end{equation}
\end{split}$

In [ ]:
import numpy as np

matrix_z = np.array([[4,2,1,1,3],[3,2,1,2,2],[4,1,1,1,1],[1,3,4,1,2],[2,2,1,1,3]])
det_Mat_S = np.linalg.det(matrix_z)
inv_Mat_S = np.linalg.inv(matrix_z)
print(f"pembuktian Determinan= {det_Mat_S}")
print(f"pembuktian Invers = \n{inv_Mat_S.round(1)}")
print()
print("="*50)
# mencari determinannya terlebih dahulu dengan Pick setiap row

S11 = np.array([[2,1,1,2],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S12 = np.array([[3,1,2,2],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S13 = np.array([[3,2,2,2],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S14 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S15 = np.array([[3,2,1,2],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S21 = np.array([[2,1,1,3],[1,1,1,1],[3,4,1,2],[2,1,1,3]])
S22 = np.array([[4,1,1,3],[4,1,1,1],[1,4,1,2],[2,1,1,3]])
S23 = np.array([[4,2,1,3],[4,1,1,1],[1,3,1,2],[2,2,1,3]])
S24 = np.array([[4,2,1,3],[4,1,1,1],[1,3,4,2],[2,2,1,3]])
S25 = np.array([[4,2,1,1],[4,1,1,1],[1,3,4,1],[2,2,1,1]])
S31 = np.array([[2,1,1,3],[2,1,2,2],[3,4,1,2],[2,1,1,3]])
S32 = np.array([[4,1,1,3],[3,1,2,2],[1,4,1,2],[2,1,1,3]])
S33 = np.array([[4,2,1,3],[3,2,2,2],[1,3,1,2],[2,2,1,3]])
S34 = np.array([[4,2,1,3],[3,2,1,2],[1,3,4,2],[2,2,1,3]])
S35 = np.array([[4,2,1,1],[3,2,1,2],[1,3,4,1],[2,2,1,1]])
S41 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[2,1,1,3]])
S42 = np.array([[4,1,1,3],[3,1,2,1],[4,1,1,1],[2,1,1,3]])
S43 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[2,2,1,3]])
S44 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[2,2,1,3]])
S45 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[2,2,1,1]])
S51 = np.array([[2,1,1,3],[2,1,2,2],[1,1,1,1],[3,4,1,2]])
S52 = np.array([[4,1,1,3],[3,1,2,2],[4,1,1,1],[1,4,1,2]])
S53 = np.array([[4,2,1,3],[3,2,2,2],[4,1,1,1],[1,3,1,2]])
S54 = np.array([[4,2,1,3],[3,2,1,2],[4,1,1,1],[1,3,4,2]])
S55 = np.array([[4,2,1,1],[3,2,1,2],[4,1,1,1],[1,3,4,1]])
print(f"Marix11 = \n{S11}")
print()
det_11 = np.linalg.det(S11)
det_12 = np.linalg.det(S12)
det_13 = np.linalg.det(S13)
det_14 = np.linalg.det(S14)
det_15 = np.linalg.det(S15)
det_21 = np.linalg.det(S21)
det_22 = np.linalg.det(S22)
det_23 = np.linalg.det(S23)
det_24 = np.linalg.det(S24)
det_25 = np.linalg.det(S25)
det_31 = np.linalg.det(S31)
det_32 = np.linalg.det(S32)
det_33 = np.linalg.det(S33)
det_34 = np.linalg.det(S34)
det_35 = np.linalg.det(S35)
det_41 = np.linalg.det(S41)
det_42 = np.linalg.det(S42)
det_43 = np.linalg.det(S43)
det_44 = np.linalg.det(S44)
det_45 = np.linalg.det(S45)
det_51 = np.linalg.det(S51)
det_52 = np.linalg.det(S52)
det_53 = np.linalg.det(S53)
det_54 = np.linalg.det(S54)
det_55 = np.linalg.det(S55)

c11 = (-1)**(1+1) * det_11
c12 = (-1)**(1+2) * det_12
c13 = (-1)**(1+3) * det_13
c14 = (-1)**(1+4) * det_14
c15 = (-1)**(1+5) * det_15
c21 = (-1)**(2+1) * det_21
c22 = (-1)**(2+2) * det_22
c23 = (-1)**(2+3) * det_23
c24 = (-1)**(2+4) * det_24
c25 = (-1)**(2+5) * det_25
c31 = (-1)**(3+1) * det_31
c32 = (-1)**(3+2) * det_32
c33 = (-1)**(3+3) * det_33
c34 = (-1)**(3+4) * det_34
c35 = (-1)**(3+5) * det_35
c41 = (-1)**(4+1) * det_41
c42 = (-1)**(4+2) * det_42
c43 = (-1)**(4+3) * det_43
c44 = (-1)**(4+4) * det_44
c45 = (-1)**(4+5) * det_45
c51 = (-1)**(5+1) * det_51
c52 = (-1)**(5+2) * det_52
c53 = (-1)**(5+3) * det_53
c54 = (-1)**(5+4) * det_54
c55 = (-1)**(5+5) * det_55

a11 = matrix_z[0][0]
a12 = matrix_z[0][1]
a13 = matrix_z[0][2]
a14 = matrix_z[0][3]
a15 = matrix_z[0][4]
a21 = matrix_z[1][0]
a22 = matrix_z[1][1]
a23 = matrix_z[1][2]
a24 = matrix_z[1][3]
a25 = matrix_z[1][4]
a31 = matrix_z[2][0]
a32 = matrix_z[2][1]
a33 = matrix_z[2][2]
a34 = matrix_z[2][3]
a35 = matrix_z[2][4]
a41 = matrix_z[3][0]
a42 = matrix_z[3][1]
a43 = matrix_z[3][2]
a44 = matrix_z[3][3]
a45 = matrix_z[3][4]
a51 = matrix_z[4][0]
a52 = matrix_z[4][1]
a53 = matrix_z[4][2]
a54 = matrix_z[4][3]
a55 = matrix_z[4][4]

# Row 1
det_S_row1 = a11*c11 + a12*c12 + a13*c13 + a14*c14 + a15*c15
print(f"det s = {det_S_row1}")
# Row 2
det_S_row2 = a21*c21 + a22*c22 + a23*c23 + a24*c24 + a25*c25
print(f"det s = {det_S_row2}")
# Row 3
det_S_row3 = a31*c31 + a32*c32 + a33*c33 + a34*c34 + a35*c35
print(f"det s = {det_S_row3}")
# Row 4
det_S_row4 = a41*c41 + a42*c42 + a43*c43 + a44*c44 + a45*c45
print(f"det s = {det_S_row4}")
# Row 5
det_S_row5 = a51*c51 + a52*c52 + a53*c53 + a54*c54 + a55*c55
print(f"det s = {det_S_row5}")
print()
Kof_Matrix_S = np.array([[c11,c12,c13,c14,c15],[c21,c22,c23,c24,c25],[c31,c32,c33,c34,c35],[c41,c42,c43,c44,c45],[c51,c52,c53,c54,c55]])
print(f"Marix dengan anggota kofaktor-kofaktornya = \n{Kof_Matrix_S}")
print()
Trans_Kof_Matrix_S = Kof_Matrix_S.transpose()
print(f"Transpose Matrix dari kofaktornya = \n{Trans_Kof_Matrix_S}")
print()
invers_S = 1 / det_S_row1 * Trans_Kof_Matrix_S
print(f"Hasil Invers Matrix adalah = \n{invers_S.round(1)}")

pembuktian Determinan= -5.999999999999996
pembuktian Invers = 
[[ 0.5  0.   0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.  -0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]

Marix11 = 
[[2 1 1 2]
 [1 1 1 1]
 [3 4 1 2]
 [2 1 1 3]]

det s = -5.999999999999957
det s = -5.999999999999998
det s = -6.000000000000014
det s = -6.0
det s = -6.000000000000028

Marix dengan anggota kofaktor-kofaktornya = 
[[ -3. -34.  15.  17.  14.]
 [ -0. -12.   6.   0.   6.]
 [  0.  26. -12. -10. -10.]
 [ -0.  -4.  -0.   2.   2.]
 [  3.  36. -15. -15. -18.]]

Transpose Matrix dari kofaktornya = 
[[ -3.  -0.   0.  -0.   3.]
 [-34. -12.  26.  -4.  36.]
 [ 15.   6. -12.  -0. -15.]
 [ 17.   0. -10.   2. -15.]
 [ 14.   6. -10.   2. -18.]]

Hasil Invers Matrix adalah = 
[[ 0.5  0.  -0.   0.  -0.5]
 [ 5.7  2.  -4.3  0.7 -6. ]
 [-2.5 -1.   2.   0.   2.5]
 [-2.8 -0.   1.7 -0.3  2.5]
 [-2.3 -1.   1.7 -0.3  3. ]]
