# Matriks Invers
* Sifat-sifat Matriks invers
* mencari invers dengan eliminasi gauss jordan
* solusi sistem persamaaan linier dengan matriks invers (membuat soal sistem persamaan linier 6 variabel)

## Sifat-sifat Matriks invers


1. Dua matriks saling invers
   ketika suatu matriks A dikalikan dengan matriks invers nya
2. Apabila ada perkalian 2 matriks $(AB)^{-1}$ invers maka sama dengan $B^{-1}$ dikali $A^{-1}$
3. Apabila ada suatu matriks invers lalu diinverskan lagi maka nanti hasilnya matriks asalnya
4. untuk determinan $A^{-1}$ sama dengan 1/ determinan A

## Mencari invers dengan eliminasi gauss jordan

untuk mencari invers matriks dengan metode eliminasi gauss jordan caranya sebagai berikut:

contoh matriks A
$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   1 &-2&-1\\
    -1& 2& 0\\
    1& -3 & 1 \end{array}\right]
\end{equation}
\end{split}$

pertama-tama kita anggap baris pertama pada matriks diatas itu B1, baris kedua itu B2 dan baris ketiga itu B3
kemudian kita tulis matriks A dan identitas matriks A disebelah matriks A=

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}  1 &-2&-1|1 & 0 & 0\\
    -1& 2& 0|0 & 1&0\\
    1& -3 & 1|0&0&1\end{array}\right]
\end{equation}
\end{split}$

setelah itu ubahlah matriks A menjadi matriks identitas,
baris pertama masih tetap, baris kedua kita ubah dengan rumus  B1+B2 dan baris ketiga kita ubah dengan rumus B1-B3, untuk menghitungnya dari kiri kekanan.

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}     1 &-2&-1|1 & 0 & 0\\
    0& 0& -1|1 & 1&0\\
    0& 1 & -2|1&0&-1\end{array}\right]
\end{equation}
\end{split}$

langkah kedua baris pertama posisinya masih tetap,baris kedua dan ketiga posisinya kita balik.

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}1 &-2&-1|1 & 0 & 0\\
    0& 1& -2 |1 & 0&-1\\
    0& 0 & -1|1&1&0\end{array}\right]
\end{equation}
\end{split}$

setelah itu langkah ketiga baris ketiga tetap, baris pertama kita ubah dengan rumus B1-B3 dan baris kedua kita ubah dengan rumus B2- 2B3menghitungnya dari kiri kekanan.

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}    1 &-2&0|0 & -1 & 0\\
    0& 1& 0 |-1 & -2&-1\\
    0& 0 &-1|1&1&0\end{array}\right]
\end{equation}
\end{split}$

langkah selanjutnya baris kedua tetap, baris pertama kita ubah dengan rumus B1+2B2 dan baris ketiga kita ubah dengan rumus -B3.

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}      1 &0&0|-2 & -5 & -2\\
    0& 1& 0 |-1 & -2&-1\\
    0& 0 &1|-1&-1&0\end{array}\right]
\end{equation}
\end{split}$

jadi hasil dari A invers yang berada dikanan yaitu:

$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}  -2 & -5 & -2\\
    -1 & -2&-1\\
   -1&-1&0\end{array}\right]
\end{equation}
\end{split}$

## solusi sistem persamaaan linier dengan matriks invers (membuat soal sistem persamaan linier 6 variabel)

Misalkan kita memiliki sistem persamaan linear dengan 6 variabel



In [ ]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np
x1 = 2
x2 = 3
x3 = 5
x4 = 2
x5 = 1
x6 = 2
B = np.array ([[40],[38],[30],[44],[49],[47]])
AB =np.array([[1,3,4,2,3,1,],[1,2,3,4,3,2],[2,1,1,5,2,3],[2,4,3,1,5,3],[2,4,4,3,5,1],[1,3,4,3,2,4]])
A=np.array([[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,0,1]])

print(AB)

[[1 3 4 2 3 1]
 [1 2 3 4 3 2]
 [2 1 1 5 2 3]
 [2 4 3 1 5 3]
 [2 4 4 3 5 1]
 [1 3 4 3 2 4]]


In [ ]:
A1 = RowAdd(A,0,1,-1)
print(A1,'\n')
A2 = RowAdd(A1,0,2,-2)
print(A2,'\n')
A3 = RowAdd(A2,0,3,-2)
print(A3,'\n')
A4 = RowAdd(A3,0,4,-2)
print(A4,'\n')
A5 = RowAdd(A4,0,5,-1)
print(A5,'\n')
A6 = RowAdd(A5,1,0,3)
print(A6,'\n')
A7 = RowAdd(A6,1,2,-5)
print(A7,'\n')
A8 = RowAdd(A7,1,3,-2)
print(A8,'\n')
A9 = RowAdd(A8,1,4,-2)
print(A9,'\n')
A10 = RowAdd(A9,3,2,-1)
print(A10,'\n')
A11 = RowAdd(A10,2,3,3)
print(A11,'\n')
A12 = RowAdd(A11,2,4,2)
print(A12,'\n')
A13 = RowAdd(A12,2,0,-1)
print(A13,'\n')
A14 = RowAdd(A13,2,1,1)
print(A14,'\n')
A15 = RowAdd(A14,5,3,14)
print(A15,'\n')
A16 = RowAdd(A15,3,0,-10)
print(A16,'\n')
A17 = RowAdd(A16,3,2,2)
print(A17,'\n')
A18 = RowAdd(A17,3,4,9)
print(A18,'\n')
A19 = RowAdd(A18,3,5,-1)
print(A19,'\n')
A20 = RowAdd(A19,5,4,9)
print(A20,'\n')
A21 = RowScale(A20,1,-1)
print(A21,'\n')
A22 = RowScale(A21,4,-1/16)
print(A22,'\n')
A23 = RowAdd(A22,4,5,-23)
print(A23,'\n')
A24 = RowAdd(A23,4,0,-246)
print(A24,'\n')
A25 = RowAdd(A24,4,1,-3)
print(A25,'\n')
A26 = RowAdd(A25,4,2,51)
print(A25,'\n')
A27 = RowAdd(A26,4,3,24)
print(A27,'\n')
A28 = RowScale(A27,5,-1/3.125)
print(A28,'\n')
A29 = RowAdd(A28,5,0,36.25)
print(A29,'\n')
A30 = RowAdd(A29,5,1,-5.375)
print(A30,'\n')
A31 = RowAdd(A30,5,2,-3.625)
print(A31,'\n')
A32 = RowAdd(A31,5,3,-5)
print(A32,'\n')
A33 = RowAdd(A32,5,4,1.125)
print(A33,'\n')

print(np.round(AB@A33))

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]] 

[[ 1.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  1.]] 

[[-2.  3.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.]
 [-2.  0.  1.  0.  0.  0.]
 [-2.  0.  0.  1.  0.  0.]
 [-2.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  1.]] 

[[-2.  3. 